name: Lint and Test
on:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/vendor
        key: test-lint-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-lint-dependencies-{{ checksum "composer.json" }}
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install dependencies
      run: composer install -n --prefer-dist
    - name: Run PHP Lint
      run: composer phpcs
  validate-readme-spacing:
    name: Validate README Spacing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pantheon-systems/validate-readme-spacing@v1
  test-phpunit:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.3
    name: PHP Unit tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL
      run: |
        sudo systemctl start mysql

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/vendor
        key: test-phpunit-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-phpunit-dependencies-{{ checksum "composer.json" }}

    - name: Install Extras
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: Run install-solr.sh
      run: bash bin/install-solr.sh

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none

    - name: Install dependencies
      run: composer install
    - name: "Run Tests"
      run: bash bin/phpunit-test.sh

  test-behat:
    needs:
      - test-phpunit
      - lint
    runs-on: ubuntu-latest
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERMINUS_ENV: ci-${{github.run_number}}
      TERMINUS_SITE: solr-power
      SITE_ENV: solr-power.ci-${{github.run_number}}
      WORDPRESS_ADMIN_USERNAME: pantheon
      WORDPRESS_ADMIN_EMAIL: no-reply@getpantheon.com
      WORDPRESS_ADMIN_PASSWORD: solr-power.ci-${{github.run_number}}
      GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    name: Behat tests

    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
      with:
        php-version: '7.4'
        tools: composer
        coverage: none

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '20'

    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@8e024bd89ff46ed2aa4e0663c6b54c87a94344f8 # v1.2.7
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

    - name: Install SSH key
      uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
      with:
        ssh-private-key: ${{ secrets.SITE_OWNER_SSH_PRIVATE_KEY }}

    - name: Cache dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: vendor
        key: ${{ runner.os }}-test-behat-${{ hashFiles('composer.json') }}
        restore-keys: ${{ runner.os }}-test-behat-

    - name: Check for $GITHUB_TOKEN
      run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null

    - name: Validate Fixture WordPress Version
      run: ./bin/validate-fixture-version.sh
    - name: Prepare for Behat tests
      run: ./bin/behat-prepare.sh

    - name: Execute Behat tests
      run: ./bin/behat-test.sh --strict

    - name: Clean up Behat tests
      if: always()
      run: ./bin/behat-cleanup.sh
